[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87f8f14673f6c6052f0db0d7088b8bb231a0f3c2"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "e26327c2d7de2d85f7f031f221cf1d3c7ae84aa1a9190df83b030889bce36e39"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c8859669a087ec4216edf48b969ac2d8e380772"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "d0af0c9619d898dd58f565acb5c4a163a87320539c880dc3556eca805afafe37"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "783c35f5b0bc7970e428432009d67506b97c81d8"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "f42419042899c3c6b1e6249e143afeb704806d22e35a0bc00a89d50a95cad7dc"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f01fddcbbce6f4a7969c25693da1e3ae0c6840b"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "57afdb2b9e5890809ca225d131d3a442d4e2a832cabd65f06bf9e4cd84eeef26"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3990e8ab1b70dfcd88d5578f84562d8aadc0f3fc"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "6ded9050c09c0444cee9324e107d3b1d805ba2976bbd9730543ed900f57e2cbf"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "337b08bb525a8b064a9474cafd4dbacf7ec8cf98"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "54aca67038f68dbebc6349fddac395a900b6486ad89886660c4463e2eaf497d3"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c07e2ee5bbabdcbe63f10b9dc89cc89aedbb9f76"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "3272070e8825c9ef28551db7c891d38ea4b4f8613ac66ec8d9b126063c5d69c4"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e779441686e6734fe6b80336a1415d62bec8ca57"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "3f6e56cfef8ca0a4b8610af9f5f40f615561fb30201635d7bdd9d24b29a508b4"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bcf51bd592b0bafed3216a332090b26916a512f5"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "622ee94ebff0acfdd20cca561002eff06d06cb93ac41d36c7eef211bdb55e961"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c10ad290fe78cc4f0c37865c0f85ee107cb9ccc3"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "34ee9a7b713d95a3741e2e5dc22dcbf67b85e184dd3c0071bc744fa446720db5"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5662b715836ef0928992833f0677e59551a59e33"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "12ddc00717421ff3d6a2c8486e0ce762e10e3efe8681c09a8d58ba6849771136"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.i686-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a370eb13538b77faaf91f9e8feeb2755cbb7931"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "cda85024eea271aaff4824092ed23c5a1f34da18ac82e1ebd26678d1ec672553"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b0bd16b057f8c6dcbe0d06b6efc322ecb22ec8af"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "f7d79069bee3d99ddde8e9d0597cd6df64643d8cdccfa07894e84e44925b801b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "309a2638359ef0e036a5e3a9b7af74a69b094269"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "85eb6236bcd8bc325a1416bdbe6fe88801d95902456fabc078afc5abd15e0968"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab8f2d1d3add879f7e67c5cf77dcba0937fde1d7"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "48f8c337fc3b1dbb09f4a398dfdb53d04706de1acc606c55c231669226e92e59"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06753af91b6c7772f137ea48c92609b3901dd5d9"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "9b6dbbef76a048613042f118f437a421a548560dc785f3179c9dbb93b53214bf"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
git-tree-sha1 = "38785dd49e422d9bd49b9639822878770b02a5ef"
os = "macos"

    [[SPIRV_Tools.download]]
    sha256 = "4f6d07d235d597f1f978489f8e9c09f2f41852fb6ec69d554b3428cbee265336"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.x86_64-apple-darwin.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7042b6c2726895eeb3dec70b95ff20f32a26b57c"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "8077452e6f0a8f02ebfb3f59e4f98025fee4561cd879d611a7aec905caa82175"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74d5e9ae9b9bcc0e810647fa0cf0f15f5e901c99"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "2d0b46418b4cb0cd377d6c29cb118dc32ed9e0cbef123a2f0ffdb10af3d2caa5"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae6c8764ff8ec979254405cc898b58ccd7a903c9"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "c464d269ddd058d52424795d2a76aa124b91e416d72abdd7b470fd9a37d01dbe"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08ab34f30c1a50257489e7e85820e1698df3f1c3"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "bf76b379659d340a1319b88d5fc774d348d4056cc9c552acfd7b24a8250486ed"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
git-tree-sha1 = "efa7229a01bacc8f98fb51ff90b8d444285a24d3"
os = "freebsd"

    [[SPIRV_Tools.download]]
    sha256 = "1e0fdb60c2810545c7b9333741dcbabc4733cc8ae23cba84d0dfe6da2bf10126"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4e02eafe92a1d16d6e2cec77128f8d5be67a814b"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "f9707d0de2773b9bb4455c7b67062c35b36eb48bbed7460374251acd713cd543"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1bf059b2834c6e09f1ace1c0371dc4f802021e59"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "679ed6d75f445ccb9aea10609fc71563445187054b74872e9960bf198ca76482"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2020.6.0+0/SPIRV_Tools.v2020.6.0.x86_64-w64-mingw32-cxx11.tar.gz"
