[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67dbceb89d14b6919f4ccda41ea97f0437c8cc07"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "7c02939dda6bf641cc13d56d5ec870e946d23607be2f02a393bc7e5ef5165999"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6429b1cb50058ec24335dc80fd07f98c3178311"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "5e588b8e0f711bd3c072e8c22a11bced12be8b33abe4dff14f9550bff5d38036"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07a15fce60efbfc3d71635056f717d2fd70071da"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "912dfd129c23c33584f7e27067974e94c6adc1d6568a6965bc1529a8523ea368"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ff48204c4338280af215685cd404a6337a25048"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "04d11dc4df83c2f1dc5166ceffc23296ca64eca64f25bbcbc37fde519e75e1be"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "41bd75b78dccd49dc8bd7ec50354fbb989dac7c8"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "a28a6c17aeee759a3018870a85b800b029d1017b23dbdeaa1ecec284afd621da"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b2c4b478455c2dbfbcefc1776cdce16be38465b"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "02ebe1aa43e2b83c062e8f8ac38500cb91c7740361864d39ceb10e1ca70e2607"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c0eb2e7186a77c51ea88fb0b99d76d4a311bf8b"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "98096705c5b57d1dd77beed71080d691ca56f71cff305bdebe1319f1b604b26c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "062989be3511e1746d99fb67887278b0bee14b43"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "0d68abab989ed4ca0eb884839c4f3ecfeb968a549ce9c8291c5a9c7c0642850c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db6828a83f525af9b9b4c2ad90467f5ce87c75b6"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "f92800839596c9b04d530bf88894876ece9fdeb4934c977ae5a6e08d3442a0ab"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f1377d1b2e742dcc6d6308c8929236f5f12e6b7"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "7f26d26749108e399af25b5f155fba756e0ac5b20e69f94f130d3aeba2139450"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1780d04b202ec7276dd4d47a9e51ff1effcb285"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "9f31d1a36e316e1ca80353f9f2e71f4d0ccd4614d3206296014271461789c988"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "396ffcc67eacb44bf12a9d9c4ffd6de782c3ece7"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "d54bc88c749cc85c52c9555a28e7c99db2d48d49d34d5262a653e7a1c8baeace"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ffea89950b7b6092421e8fbb7bd08acc8e2748c"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "e9bc7dfc213c17aa248eb03d9fb9ba4805b5399ab27151ee185fc9c6370dfd0a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.riscv64-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d01e7623bf8930ae8f0c127b5520f7c15727d021"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "aeaa15e4a652a7f989515653ee3b8450d8b87434d640419c7fa989b588f83f68"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.riscv64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce403f566760157ad279af6faa632a6c0447eaa0"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "01831dbe2c5be0d1ef3bea1cc7d162d18a2ffc1b9ce7da202e68f7a264b7b4f9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.i686-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11e32b55542c88249d72aa921e5d376bc6a86cbd"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "a5e6272d75665bf879837e2234b27ddafa47a109f805f8a222502de7f4374d89"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7703febfcb53758ad1718b5e92ee548a0c641ca5"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "761d476641d774de6f7a2320d90bffdcb010f8440a8240f06014eb463e4aa9cd"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7814d790d2e01b942ceb36022c64ffa9b9d366c"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "7903d5ca16fbd5d2d2db7b914b30239947ec8f3d9d01b5f65a26439eb1be319d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb88a3232f8494c81bc55608a6bcc2c1db7d6f0e"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "83726803510f1e3206deac5de11d0138782c8514789969615b590da7ef1dee48"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50255b800424f16118bf915c1636bf5dff9c630f"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "f851e9446cdbc3fe7f431dc9afb0956bb82017080e5e87ddb2b59a230f12de4e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17200024c152b28ffbb0fb299851d554ae74b633"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "95ad991e84a0f35a1a88b12d7aa756559099a63b74cb5873668983a2cf0e7c85"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1748a195bb57c61b56e01abeb341c4b89cc109f"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "00fecc9de5910d61743b42b68eff9131965d96566b7b59852c5586971ff6e894"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a2ec8d542f8e2d784d209f3a1110aec9320a22d"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "e470d8032df9f742e48e442ca69694ca8469d6d3387fbae86865d444e8e8118f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "548a47fb489a45a6eac9e34e3e56b2444de4ca4d"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "197af24e0adc86c492ac431e83bd692164bbbf280b4f07ad63abb66ab186e339"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
git-tree-sha1 = "f66e9aa3a5b4d4d072b34f022aba8fe4487c408c"
os = "macos"

    [[SPIRV_Tools.download]]
    sha256 = "a2734b99ae8b9db53ad5e4353f9aee433334e55509bdeb500365805df82d4dec"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.x86_64-apple-darwin.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
git-tree-sha1 = "e14e1e1b268a9d7a27a98905819812c619d82441"
os = "macos"

    [[SPIRV_Tools.download]]
    sha256 = "2010e8caf3712526fa66dcef50d834ede9a0966b1b5ee040b49f8089e93cb70b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.aarch64-apple-darwin.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
git-tree-sha1 = "0a35ed28257bdb3c9ca60fc39a8c5034e9ce789c"
os = "freebsd"

    [[SPIRV_Tools.download]]
    sha256 = "3916f7167e97d875766c6d4b345936f3a77cdc6a6c4395588375feb6b6752292"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
git-tree-sha1 = "aa51e341ec07ed8ea75f73dfe7678db560e933e8"
os = "freebsd"

    [[SPIRV_Tools.download]]
    sha256 = "2a3ee8627ed6456ce5a407c4b9619e298a4ca8e92d249da80486912d697c7c09"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.aarch64-unknown-freebsd.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1460b0fd606cb3040e5868b0788a0a68ac249494"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "77455ae23298bf9cd578d75c1d28d946331239ce2cf6c9c50269cf0c01706025"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a56c5269d6e74ca847cf3dcff8f654d2a174394e"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "e3d2aedca86d01c4ca94b6655ed39bbd6b1a05ffc955b29463f1bf2a4d01e22c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2db1f6e6428d909c30b793fb456294b64b9adad"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "7b4ced96ec4ac355c236ca1810ea618701c6577fc7ae93db411ac7a9bbe1fe2e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bfd2f2f00cdc057a89c30b09a01791578842e278"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "a2aa85692a56c857ab339860e9fed21d2cea92236485bb288f60fa97d496bc0d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+0/SPIRV_Tools.v2025.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
