[[SPIRV_Tools]]
arch = "aarch64"
git-tree-sha1 = "80639ab1ff0018cf32abeacfa25921a692d0ff57"
os = "macos"

    [[SPIRV_Tools.download]]
    sha256 = "a9aa1e855cdf829856722011392fae141c1b4ad4514706e1aaed5ccec4ac45cb"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.aarch64-apple-darwin.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff05044f861c75f28338b81ff6c367e39bd3e372"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "c7a7558ca8322eca6811655da2da0b5d04a98aeb6eb27dc86fca523856d64ff0"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9687e83668b9c3cb520085cf1e3ee01aa2640571"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "db534634724404b2f3268e825f71f298b61f71a3c238faaefd269141bd70931a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7498d3c2e42ab6643619631ca159ac5a858ab4d7"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "a7fcc527c4a7a65ae53cd1019a53686d42dc35c9820eaf93009df039c1fb8597"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7d943c11050fd79e8f33dccff01e459676dbe74"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "7f8a4ddf7176a63876f581ad73f6efb416f07b719c25b3305f0d935838da8caa"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d05ee7485b0dad34f52042e18b48a0ed9a1d55a"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "50c534b89bbaf595ee65138eb9cc826f76c829364d991b3c6419fd329e4f1522"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd2d016068cf5169e20f09d913e746d6ca0d9925"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "92259989b1edf618e5238f3207f23543cc35b9ab4cf87ea45ccdf9945a4f2477"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b2f28f9d5979ee0e3cc87e2ad300f06aa6880b2"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "49f954c72b96dc699f1353c6b1289f22e5c1ee32c0190ab1ba1d908dee254aeb"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c09266023ca7cba657712ed4b18163821116618"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "ca61bf66359147c4409f260101bc1c5c4f0cc86d6194c6b3429a07be8e930da6"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e04161c414e129bf29f3e3dc7b3340dfede116b9"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "917fa21cce2bf300c0535507a62c4bd932bd482423c6fe54b0e9f13118b6e190"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51ab99f0b469d957a189bc6bc522f209a0897e07"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "fa4913976c4f2a8055c28e68272b1f23e6827ad84850ff0ada6344690044437d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "24edef4b440e39b41ee919571f40762ca2efb951"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "3c6f4420e903b80136cec13b0034591091a4087f374ed5199287ce5f8bdbfaff"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51e11b5163ac4a0a1e56d3df3172a66cf851eda8"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "a5317d0dae942087daf65c6ec28ca3e04c406ad14481e09024864458fc18f63a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df2bdc87308f80e2cc4abb8895993477f99bd3ec"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "a7b0105c30e1eba2cd0eb13c19a26c7aad21a9b0c4f9db4370de244d7f42bd4c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0efe5c4ad583554c2dc5f9bee2f0d7c590f131b"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "06b3a586faee51725e533c16555fcf92f53a43ae5e4909e97cd87b86fc922afc"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e2843ea36a9a95e7657075708c2f5b8d63f7f17d"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "e3ea3f766e33f6535bbc92d04dd26f64376f56593ba206d83f0a5be3c9697850"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.i686-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "597f9680cc3f607b561015dcfe2e494da50e5f0c"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "ae587297ed6e0d64c2b449ed0a3c8ef2fdcdf65798f8da6e3aa80f27a85179ab"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d8d94a3fb01f63748980477c0186540c1b52878a"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "a0297a11c3b1994dd92530aca6898f2145dc444afa63ba727e17c2ab214a21e2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "848dc99e6d89fd61bfe494b93dbf38282713d987"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "70af00a416f0d46faaf4fba7e21bb0dd9922e11b0111a4dd408070764c1c5012"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8efa608c9c3bf96bd85eae9244cf0c758d12867"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "6df0decf9b49d5b8ae11c2a8347dd4430bdec3a393e01baede7131e480e66e55"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a570e3d4fe2d4dd57744d90c6cc325841bc5cfa"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "c01cdf3d3b48621f0a56c3ab8cca900a372a57830641d874a57d10739f7b5b74"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
git-tree-sha1 = "4521bed8cd43c58533fbb01df53df490ecbd3836"
os = "macos"

    [[SPIRV_Tools.download]]
    sha256 = "08fcf2df70cc668389e1eddf2d74b3a9ad5dc83e8c1be4c0e2deaf915d3ffb8d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.x86_64-apple-darwin.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a95ca3c83b2b8707ccdcd702ea95f86df4817203"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "317c79049799e27f020ebe5349e9a4389f3dc1ffd3d775134a7aaa2d43bd3059"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a573c167fa93a3855041bcb9c757224914b8f75"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "1c3a645f8d4efea017cc97141af7ccbf73ca089268b50d69ca00d1b0c4ef0407"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f19025a208398a610a690ccaddfabd72824c515c"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "56a5d94fc2475456eb28e39cbce04fd1a0d3be9ff8cc9acbcb9f0f2085d233b7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6921cdcc74cb52cd4a546650da993aad8ed500c"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "db61c6a47363869eb709d39f7ae0bb854b77f3a6bb812a917625550902e4b465"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
git-tree-sha1 = "d9b6356ef07d1c448e57a89f959d884914d725aa"
os = "freebsd"

    [[SPIRV_Tools.download]]
    sha256 = "6f2cdf93f5b146d6a490e75a4357c81eb78999ce11cef407647ef3c63730c3e2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd05a63480017d11fc6a312dc0d9f91b7a99040a"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "cccd709e8bd9f174512ab547bbfb34512afef02b2ec025ffd8d317ca9c8ecf3a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d9f4dfbdd9011eaaf288741fe2f30e667879f72"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "830eabe913463b18ac2cb442f129810d51f53ae8ad9b2c70405b82c4c7792599"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.2.0+0/SPIRV_Tools.v2024.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
