[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "24ea2133c2d00f50088cf635e6a5949b2566419f"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "9c23dc9f350703effe3437439d5a38ed76306040bbe748038c47abb5f38c1805"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "535230ac50c6832b069b70e02a3a180b1e111270"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "fd147eaa612d1db5b9d5624c8629603d0d297860fcad0bc5757bd6f56ce04f9b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c0cd4a86c2b15433a68e9221c77d53084baceef8"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "286de94190605ad5cd9f0e1c9f4c28068972adcc9426bfadd10776d0d2d4bb7c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "954f1d0245f593658ca964009b1b0c17834a59a7"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "ec727016cf0098ea9ab70bdcad64ea494e3707fbd46406013d01139a65db325c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a80351844f5af861075ad88e968f6960912d963"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "54bbc14e6be24b7bf10f46dc2eac0e188219bde157c1d1ca660c4ca0025e8cf0"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e75fd5ab774c14d8417df4dc2d83167234cb269b"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "13f0ce7034c0c7d6da50100dd78faa7953cc3541d5e29b31e010656d7ae83aa0"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37ba08c39581527991867c34ee88bda526a7df79"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "61825d746687964fc061c73ecdf5f2dcd11983220f28c2963186057edeb0e529"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7dc758a11d9579e5a4f093ee611fec876a7b570"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "af0a054d124230b8282cc9a0e79ec249ba71792a8140a6ee013fbc6dbef7c91f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4d61c294396f2f98951a1cb9c8d67bc15644821a"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "a1907f9d966a9195a46b6a2be2aaf7fe8fc83db7f0ee855b8bbfced36cbf1c0b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d8c52f775b2c8c83f0ac056c819c36a621f8ef6"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "54b1eae30530fa7ad6dc5aec65faddd9dc4ad36a394a19b0bb3469992f372565"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03576087bc0ff15ce249b193139b7c66af1be623"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "2c165a3bbb34f667a43df9ec8a90f3105fdec2babdd01d8ecdd61f59c2401565"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc1e199891446950f56404af27ff08b188627d92"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "871f694125b9196e0719169479a62e67a703444c1af8d2e60dca1b2e34d506a7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a9b13723e3b74661d797fda18900386f9f3a8b8"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "8f438a74ad9bcc089229f4dcdf636d8165832cf0ddcd134320678aa5028ab476"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.riscv64-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02f25a563cfa5279a7d741ac8e5fbf33a317c0af"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "550997ca635b948a82ee4616176d4a2683e3ff65f3c30516a2779139b74289cb"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.riscv64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "732bf39f8b4b5dfaa9f42866ca166ab283b44530"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "71d603f61074bc97c26e2328270e720cbe6975433e0758d26dba34bb94f85a06"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.i686-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66fc318e23a42a607f4f0e6023c66fc73d9e1026"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "915b6724815e65f290ec4032f9c2460bf9ec3f47b84342bde15cc8d65b65aa67"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b896e0b336dfb1a5bae9ba3686dfb19fedd9e1ef"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "37ae0835422ef9f533b38ebc7bf41cbf8d46ca2c0564864d5508b4fbf0e9c0ca"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "789a9888e4c796fbe671937c14d60efc19849120"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "70ee0f9295afe068ad3e907b73fcd31df2323cb1014db164c0bff0641b37b174"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9968f38a165f9a9b86e0545b6c3f8d9c790e4643"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "beb8412fc477d8d6c79f28ba325c874d147b532c18afa460dec380387218cf2a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bac36c7dd2149dc96b65170314c40b76a2fad489"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "17b63f34e5049caada4939e22fbb441b9474fca3d6462d3420675cc68c9e3a00"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c66d2a8e228ecc06fda277ea813efa405331aa98"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "5afdf8930570f742a6bb40e987f232018588e98561dd74df5f8d65fc216e4016"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f13010ef40ac5a89ab786559849b2ef89ec6eacc"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "e2ad119cb4a4777bd3d06c0608a13f47a81a72862fb709394ea429c39385faf8"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c50a1ab1ce24ff56d9c89a3e2611de821099f34a"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "276689a1d57d08e5cb2df9ba6256e9192ae6ef1f39844622edad2255d7dab9ea"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2074b3941e6660e15e4118aefab1bd2be60f02d8"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "7973ac3401b3984ab73c8875ec6d68cd493e05d2f966a6e1d4f7dd5112295ee0"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
git-tree-sha1 = "27bf839f62a69bc5ebaa54fa5ecd632ec614fb47"
os = "macos"

    [[SPIRV_Tools.download]]
    sha256 = "b34b07971feca9ba9b169cde8c5c49b67a7d7436ffcb463352b0529730469209"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.x86_64-apple-darwin.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
git-tree-sha1 = "ad0fc0e3fd440cfb70986078ee4e0b95349876b1"
os = "macos"

    [[SPIRV_Tools.download]]
    sha256 = "695bed080ada7b48edd389394488ff7fe2da2d6ccbc154f6a03b5ded07102c75"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.aarch64-apple-darwin.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
git-tree-sha1 = "ed21fc525e4150c283e16b54c345628a8a61d702"
os = "freebsd"

    [[SPIRV_Tools.download]]
    sha256 = "0c6b2b1f31ccdcedada85608a6313a9e40af7c329289df87841d34349d53e44c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
git-tree-sha1 = "231ea7fb3b4c32e5a8eae86122be627ff120e818"
os = "freebsd"

    [[SPIRV_Tools.download]]
    sha256 = "ef207251ef1b32e23a88452af95875d9978f359b458fbd42e967506a09dcd99d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.aarch64-unknown-freebsd.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "492dffbe00aa067912c489903bffa5c0eca1d302"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "b53c387d5ff1b31b1daffb1a8dd103060112167826cb3cb9b0dad4df6de65319"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca41b0c0edb28a866aaf9d2cd46c9bd0a605a167"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "f44047cd18db063fba8e37f4fc0236013a8379f55fd8d3b89349f49ac86f7a86"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "41767083bcca30609a0575403adfddddb71741d8"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "9bd2740318a49640b72c41f05f36111119392d096bdd678f4fd6e63d7d6a18f3"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12c880a5af19e67d3cd0d0bd265445f96ebfffac"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "2ae84aa72c937ac5dc48d5fbda74014d26c588c5c30eb177049dd0900cef4fa6"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.1.0+2/SPIRV_Tools.v2025.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
