[[SPIRV_Tools]]
arch = "aarch64"
git-tree-sha1 = "736748b40b0a88d87e1d3beabf43436b9cce02b6"
os = "macos"

    [[SPIRV_Tools.download]]
    sha256 = "ee8ae81ca8ff5388f59f81f21ea53b05e2c984da54319b7ef7708bb0cf3527b7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.aarch64-apple-darwin.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b0a1e32aec473541e0130ec639fdedb9d11f8558"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "b2f9590968c6c655905e6543e80de23d2b4ed5e9a31c99c73677e92520c86df7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "864cc48ddd15b64df65c31d2424a8d3d29b82917"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "dab8320519060daaa5654ecc0f52631e23af333b51c9d404c488dfe9562785fd"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a0823299b382b53ee7a569db397a69e5259f810"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "8db32c5daf0970391cbe998fd67c552567769fea265f3a2046353ba2ffa01285"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "114e3247b7f37775299df4d712285968dbd54f40"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "8f89a16a3074e116cc46f489fa6e8d848c2abe3849a1ba474a10bfcf646918b0"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
git-tree-sha1 = "90c05228fca76a32c747a7752fcd308b0d87e1d1"
os = "freebsd"

    [[SPIRV_Tools.download]]
    sha256 = "af06bcab445d518f9cea2dc1ba579a33e984aa3775e1b7c4109b847fc639fec1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.aarch64-unknown-freebsd.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9dfba0b0e8777e0f528819b4bbd7d148432fba40"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "c3383111a182f57c35a61545dc126b8c9af2fb05e08087e616fe080637c159f9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a0ff55ad0213afeaefa6dda79c0780f5107e5927"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "e812ba1f00adb978efc870e4610d90cb6e1fd18fb81506b240c5ba460aa2c712"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "faa4c84299423d87e19ced995615def55add1d89"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "dbeae4d28d94911dd7f38b4172aa0196ee2f2c265696a773ce8cbd382bbefba9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34357932f234f6f150f2e64dc207ee9faa0b715b"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "61cd2523c706f54304af76ba7b8f0e85f2d013702a7cf39197f94fef061ca401"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af8485fd7c6a9045e0a9c870c12a5ba455999e1c"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "9775a4176a43f7099953e1457249491b4d1cb9d03989e6582551ade6193e001d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0310d1969bd20194f8a35d583911c7d845f6792"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "74cf01490bc95bf0defd8881b3386d8d56878c9e01d1251d75093af78493bbbd"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3260dd2752952c6002f5844b76ac2e4b2c483a79"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "bfb0cc698b09c30d713b86373c09d9f5726440aa5d473579c6795fb442c4ae98"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d71afa8e7f9d9905c39bf62fff40e789f834ad14"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "8e24c4b943e8ddefefe2712b1d6ece0fb2ee2a6dd74271a5bb908f6d56d92895"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cedfd8a5730494cfcd40c475b4361aec02965ef3"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "d744b96e654432038dd64e5e81d98e22b8dcbc5d72f8c025766696bf2a0e672a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "478361e5b477b91b67cb7f8511425d6aaa9b91f1"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "895882e5630b73f7eb8a453eb6c1fcb4e255696972a52a5dc236d544e91b2f2d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f0a041ceb11bb57088c141221baa7b72480ff8f"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "4c672c03c92ddecb1bb15101e8b80bbb63478a742c65023cf8d1a3c6fb78f8d2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.i686-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0caeb94d9163716d1275b4e66fc6a7e06874dc79"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "5dcd776f7f423f51f8ec2705bcee2d14c65cb1c540fcb0d068a8b118dc292282"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b81221ecb3154e41b64f535362a845eee993a0aa"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "11be825f97fd7e919b498b020fc434d1053cd6315c164df5397e41af9bb32069"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cca7c4375a0aada040dcdebaea5d98231c3123c5"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "a0bb706af7040717c23c8ff0592bf9e2163ff63cee971bc28122e6355d27578b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1548517f7a4f020ac95c187bc45f541f27fe3f9e"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "5e59551d4ca17d11bc4a06542a132e98e1e8c1a9daa71d4a7438ad7e4962a9f7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72aa48c73e63b2cbcf9cf09e9d610e53a01c21b0"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "fceaa2c74cc9557176a8837e4fcc074df841ac1c4a3cefba0b00fdda098b4dbb"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd44dfc5bb6113af9f31eed16da8c45b7b9e7a36"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "5d70e9005d81596d41d36667ebc910eebe40cc851707c8c7091d107b0c61d2c3"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.riscv64-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d70d0e880fd74506e1684affda5d399b60d23f13"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "86de096861108965c44afd58f5e345e4df243591ae22ba8b5bb049b1979abf7c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.riscv64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
git-tree-sha1 = "fbb7ee1d9acba63123cea4ac0691e100588ad4eb"
os = "macos"

    [[SPIRV_Tools.download]]
    sha256 = "7a7f4761f74466e77f2ee6ac6b3dff3076d0d11f6aa1bb622e807419b8df78b4"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.x86_64-apple-darwin.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5fa031f2171c1ca1eefa7f100c6bd5b525bd9ea6"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "1e75462a226e5b87d49727117dae130f3113e476908a0974051971c2b1dff453"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "494cf88a9175f106042487a2453249e771fe49f6"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "ad233b8cab216c3812397883cfd149cd67c10ca71b6b07384bccb36d627a0ab6"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e885a7b84fdbc2a589d4bb3630712eaca7eeb37f"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "f4b1176ec2c804ac080eabd5075e7f32109d918b07df2ef9c059248c212eb8d1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "227ca5c4c515c65c063c116e28717f6bcbe24eba"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "98b118314624105195ec4040718621d7403aac525470ddd7bc335ff50d0116dd"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
git-tree-sha1 = "2d10856bfea302ca494c8b914a663ebfb31cf170"
os = "freebsd"

    [[SPIRV_Tools.download]]
    sha256 = "4a283349cf2e16acb5e712456b966a12ecad563b83960612e5a74ce50e46f5d7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "adc7576d08b2cdae5b6dadd852b144aacaaf5f62"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "37ec1f5d509f417e3d9e19345ba4d1073aa6cf4c40baeb8df2869d19af43bf23"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d79c76ee4eed33121a32a8a6475e4a71f44e3ce8"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "466db17d8bbfbcff1284f681c578b911317d0de4e57408c12fe51d543b24cbf3"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.4.0+0/SPIRV_Tools.v2024.4.0.x86_64-w64-mingw32-cxx11.tar.gz"
