[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ffa60df84ce313ffee26258e63590e9ad305705"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "042b85a578f9af92790879fe7e84a1b75f0c79426b4ba8a81f1da4352ccf26c9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a213311f0fe01dbf62871e4dac545641c6206c1d"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "caf29a7449a259b8af17e807c545acd1511f02763ab01cece745793c6f489f9a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4702837e41fa54978eb57b671b734945b875e5ce"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "950fd7b5242e52d1e52102a13112e70ce9cabb318645c55861f3d030893c20e6"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2c2842577e8fcb702979a1e97dc2a8f247472a0"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "768e4f4c3e97af16f76fa0a28e995a77fd4eb82efff459443aaa8973012c21ad"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4d5426f4879e24f681262a647bad4af8d934c938"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "ada64da5f292294b3a2310672232ff1bc2e092cad701504b1846011eb3d9a5b6"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52498ed1f4661704ca25fa3ae86674cbbf844891"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "0a9461629551836d141b58235b46828944507ec997d247d596276a9368eea5a5"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb45628c26a845d77094a9fac2b83f4f2bab4232"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "f9ab90bd0b3de3bdb4cab40cd55b32cf5f88fb656977aed8736e2fe2ffbf72f4"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83a2a590ec9c390a49e6521695506b4dea532b1e"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "9859e3cfa31e00685bd3cd5773c9283fd9c676ac7bcd9e2116f092445d02dca9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c6ffcf0b99234c941af91be38397f508785a0aef"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "749a11d2854b2d75e9fb29a19d71b8175221d1cef2e33eab3195238dd04d4ac7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb44747f210f38cfeae6ba97c1344698b0c45d58"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "159c44aa0b562928ac45b5ae96e8213a1e0e7ff447914b5f99fc81c219de9de8"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "698c85e797216946fc422b6f2e95b397dd10dadd"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "8caedbbf5a8b698c2ee91d050db5550d552e5f4d8ffa58ceea56e3cb61728095"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.i686-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a27e2ae4c84ecff33382d15c8c6aedcd1bed937e"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "765968828939161525e6e8176d8766e6c056a832c29b6ed658fa6bd561f926be"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "53ec0ae6fcf747fb08d943dce16da19e73c547f5"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "0224165abfb0fb59d793a35d35bd0cdaf0e7849595f90a01b210ccf1c3b63f92"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d60e96913709e11ed237c1406a7bc80e1d3ad61e"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "71d845ed46afbc2d09b64245bbd52fda5501369f021a94b9a30dfe2aa6db1c8f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de86b1e9eda9d2e3b874e8ece4e830f33ac4a3be"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "e7465ae795e0dc396320e03ff8d9c8f07cde71fe8ba6ec4e5bbf224c3247656a"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbf96c62c984473773c3e02b1a9a1fe73090a098"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "26173245ae589c612bda5f79f2be683345d886c1c06091de92a9ccf0eed8a3f0"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
git-tree-sha1 = "a508103d388562b6c3f4de7ce7a408a8948aacad"
os = "macos"

    [[SPIRV_Tools.download]]
    sha256 = "b06adb242e87402550fa360bad490caca3b1007b3f68b106bc25643e9ac47649"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.x86_64-apple-darwin.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9b44dcc55a831b44d84794cd306f79bbfb4bb27"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "8e2e62f99596095692c01e5c622d50ea38614feb4f9fdb40e024213e5ce9c67f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa3cb39b2ab0052c55e8400c4ba4a434e3667b8a"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "8bcf35b14f909d77eb36a26d5af25d5e85daf2aa91c825c32dce1a10523f8dde"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f2953dfc064ef0ae10b4111fcb69cc6d5fbe830d"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "4d516cd540717cd0e281bf7dc94601a2a3c641cae047cdb7bb758a817c192543"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b18bc8133984863131a030b8857ed70253a104e"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "d4c986c3c950753716f4e5238f68d1e81855820d62b8703701e1c9086b35191d"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
git-tree-sha1 = "1a380a24e167c600b8353e5ddca3e31a785f7505"
os = "freebsd"

    [[SPIRV_Tools.download]]
    sha256 = "7fe3ed5d2a84216e1431c6c111d4f3ab0a89402f59a4081d10b4dd663648e7c8"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bee29bab32208001e4513ef087f206fed91e3f37"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "46ca43bbb97c639fa073cf0b124eed0ce45211cd5310e983823ee198ba728b26"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91f60cea19071efb3353c456e565e6e5e80a0c10"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "3f7079fbe969c93299e01c5361ec5df8cf6f2611fa02cb01139beefdc94dc544"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2021.2.0+0/SPIRV_Tools.v2021.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
