[[SPIRV_Tools]]
arch = "aarch64"
git-tree-sha1 = "35f45986a472838d8c432ca21c242d904858bef9"
os = "macos"

    [[SPIRV_Tools.download]]
    sha256 = "dd379e48c63b895f2cbe6f94ce3f5de7d5c4765edd7fa20abfa3ff3e4a9c1691"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.aarch64-apple-darwin.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37d26f0aae2591a6cfbdef88571f4caaebfed7b3"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "68396f77a28b75c4cb398a1b7432ef16a84c51d4883346b258c0f9c950368a48"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.aarch64-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94a84f89d566710b0c17da6012ae14179df2c80c"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "f09e1689ccef27b4817eca0c54884d552337405eb93017eea4db86f6f0606506"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1cc8c16846efb0ffb7c23e19675e8d83323f5bdc"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "493483f14015bc7bce98d5cf2b77dfecb1366e158df85eefb1dd3ed326bab374"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.aarch64-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e74f01ea64470d6befc324ce419fd8da7e57301"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "bcfd737cd614c3b4c3a24d168f85888e678fd2b90cc5272af9097389220a49ca"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
git-tree-sha1 = "799d61b9ba7c5e76a4aa3dbacad1df97e479fb6d"
os = "freebsd"

    [[SPIRV_Tools.download]]
    sha256 = "c524dc4258eeff552123c9d29a92d85a20f840023ddedca9d61f58fa47a31957"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.aarch64-unknown-freebsd.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc0da201fbb7984c6b043337582b7626c3a936dc"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "57a9d9770fb0a9c5233ff51813292e2a9262d7b342ead79d9bd05010efd7ecad"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a4cdf4a8e739286a6f6936393bbc6708d04d0ac"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "e596d08389eff45e0e2058d697dc29aff87f869740ca10720c8db3d899d02dea"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d4df59a27cc21915c9fdf7b81bb50f5110da1d3"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "39b22163a1fe96c0bee17905c8621de814b981cc4f4f9023bed7fff8ff0800d9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1bc4751f633b58e174664038429fa4d92039acce"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "9d97d775b6663c3c2ac39b4532daef8e6ac8dd2a912217230793265f1d561f5f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0d1f687b7bc9534d669d35931775edeaabebbcfc"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "7dd781a0aa196bba719ba86541d36b99445f4f1672ca5eb14f59dbd51be21980"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e282274dd1eceef1e0d8ef2e01944c55c05ee830"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "14403f19fdfae2c3b220625189e30c2679c8bfb076a44ec7ce3a3ea1a0ebbdc1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79c7cb6d65dbf3a70025032475edccc77e79c22d"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "f6b62cbb749171066eef074418fe26921ddcc66b7039f7f29bccc066e6bcc73e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21e08bf34f5aafaf96b04e81e251f9771ca42cdd"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "cff75b252f5bc3e58356a7ebbfb107a75f9b3537a954d4bf231024705c353a3f"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "04745323e6d97229d4a0e32c5424c907604a28e1"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "8cd7d7df8779c7689c0cdf6fd91e9a5b39fde5b32803e43af0359c2686ebdb89"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.i686-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf22476543f028db9ad2e15bbf785602b5c475f8"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "b70f547e3c0ea9db782ffca549e390242d17df34a9bd6fdef9316131128314aa"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c700ab89828db7d7d13184ea54b31e19b4b2e6fa"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "d6bf58c9540a754d1b971205705b72dd66f1de0edb2e9e9de9a39d14992cfd89"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.i686-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "231c643f99f747a78ffa2775a7399814e51ef898"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "f25ac3bfff9c3085026fce5755659165fbe97c986e3590b4c68ca2bfc0c7416c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "003554614d49536327a35373b50d534c23e659aa"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "c2480d78ba0d717c43e8a1702e6371d356f7913f41f6c34abc5659608ed7c105"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.i686-w64-mingw32-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48a5d36819f06ed74a418a23c7ce3f91767e93d1"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "78956632e7e95ccf337cf57b4ec65a61a7f378c56fd42598e478beb5759ae733"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ccebdeb04ef60413cac5a6f90e0df064de8f9cf5"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "71b7badf26156c68a68b3b1fb7c5581bb7b194fa5dbfc862d66fc7d878f214d3"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b85e63da562b736a50303770637deab3d7a9089b"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "bb853028ee186bf6da24a95f044607b1c6789fc840a408441db4a88f0fa07ea8"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
git-tree-sha1 = "b7a18ef6a9827f683d71f6d6ad0985d316ddcb23"
os = "macos"

    [[SPIRV_Tools.download]]
    sha256 = "0b9ecc77cb0baa352007fd9844e4fee1c2034cd11fe057048f41b0b70e3a6bf1"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.x86_64-apple-darwin.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b5c28aae4cf43e1dc632ab4b04a9d8b7cc1d69d"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "7cd93df18b0c7145be6ad5ad9b8e4d716f789cfb134ca1ff23737288e0bc31c5"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.x86_64-linux-gnu-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "219e1b9a97ec75f861da593f90342137d6c34644"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "eb3fc6bb4172bfb8bc6de61fe12090f48ede0c5284674d4bbc2fe63b4b5e55a2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a49aebc7deed92a2cf28ef2583b46d80ced45c8b"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "fa82bfcfef7953d385ee42ab49c0a0967694b3f419229c2f89945d42a0f2d0b3"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.x86_64-linux-musl-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c45e5459f7cebc1673afdf9edd6f2ecfe9b56edd"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "6fd8df9600f02e791c5964656bc5b4b25d6f89d144b945d8be5e776068e10370"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
git-tree-sha1 = "a0ae2cce484bde6f65dd193e11b8d5c6aed0c2ac"
os = "freebsd"

    [[SPIRV_Tools.download]]
    sha256 = "2d594240c9bdca2dd86d9d69ea6e081b9df59b17e3d64d21ea4f5828db7d3afc"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f7faf6e8a1f0b8c0494b79d535606a2c34ab5ffb"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "fc13e424b300cfce92a5d67f136d251f5ffd4b109750242f811269923776f534"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a3959016c76ef0c27566dc5d175e8f7594f117d"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "7028d12d273b4f1910d733cadd1677239e41fc849ceb5cfcef088850ff324d80"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2024.3.0+0/SPIRV_Tools.v2024.3.0.x86_64-w64-mingw32-cxx11.tar.gz"
