[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d12aec1e21ddfd9898f0bf549d447f0a5b83dab"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "80d0d631fb553ac53730acaed543894214d5bad237828452cd76c6de9173c5d2"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.4.0+0/SPIRV_Tools.v2025.4.0.i686-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8769e627f0911e0e6ab9b58f5961768a06de3e61"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "168d51d9d3f665e9cc1e4cfbc695a1b39362f6ea8ffe0b04c117ee5af0c58e3e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.4.0+0/SPIRV_Tools.v2025.4.0.x86_64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef6e041b07b053a7ab101b48334b58d3b927d7bd"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "569be548ca705419874aecea3cb71f58ea8c234b75796208f09fb0cbe11a907c"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.4.0+0/SPIRV_Tools.v2025.4.0.aarch64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e30b1887254a39ded34bca7f81d2a6b2955e253b"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "ce1fb253e25dc5a1df82f481f97dd98f0ee78940ad91e53a169aaca946ee60f6"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.4.0+0/SPIRV_Tools.v2025.4.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b1ec7dc6c67c2c451f317d0eb815617b2a8510a"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "cdc877944eb5f2dd92f9eedb757e0864920730f0875366ef314be97468e279c0"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.4.0+0/SPIRV_Tools.v2025.4.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9de5221c10ef2982fb807656cf1f9d66289e4167"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "11f45aceb842c15f441c9b4bccbb23553be579dfbb975afc1105b94dbe9d07d9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.4.0+0/SPIRV_Tools.v2025.4.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5ea63e9588852ebafa112694434d3d4efecb067"
libc = "glibc"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "64b54e576d418efb7048c7334ce35ecec8e487e4f77cad5585940bd338eaf94e"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.4.0+0/SPIRV_Tools.v2025.4.0.riscv64-linux-gnu-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4ab10a5ffcc17d17767c6339b1c375a29f562f1"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "f8434b2b30532a59a98dddb58fa0fd0bc57d8d49a8fe5035f6ae2928de162ff9"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.4.0+0/SPIRV_Tools.v2025.4.0.i686-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6501a535fcf418c5e01633b5c823b05d0dbb1157"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "16f67408277616d8167121a77865b6303c9f0072e218170a343048406d34e602"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.4.0+0/SPIRV_Tools.v2025.4.0.x86_64-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c40642c428dce9947956df783899685ca8f798d"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "c8ac1574d1db67dd4dc8d74523b0522c0f7370d31f11cdba34099003559f5ad6"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.4.0+0/SPIRV_Tools.v2025.4.0.aarch64-linux-musl-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3f5826cd4a56c74258b52703942ec8050e45ef6"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "7077925267150d4e1ee6c70f9823ed36f2b5fe5864e72461d4464a903831123b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.4.0+0/SPIRV_Tools.v2025.4.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9129066f448800ca462c4feff731276b7219c00e"
libc = "musl"
os = "linux"

    [[SPIRV_Tools.download]]
    sha256 = "a8b41aa1b67fc9de5f7fa414a73c5a65db87400476509b54bd9fdffdcfef9296"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.4.0+0/SPIRV_Tools.v2025.4.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
git-tree-sha1 = "2a4abcd5f84a7b627127d0bc2c7bd0749d42b59c"
os = "macos"

    [[SPIRV_Tools.download]]
    sha256 = "f678580e5afed4ce01f07c5447e87a142bf2b93b3219aa19bb1bd3b0d9f3a83b"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.4.0+0/SPIRV_Tools.v2025.4.0.x86_64-apple-darwin.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
git-tree-sha1 = "ddd75f95941f88c2c9be9d5f4b285e8cc35b1249"
os = "macos"

    [[SPIRV_Tools.download]]
    sha256 = "7be2be9ea74b80dc43e0cd0671a8c9f4c896b1de233df4e6c468b08aecd3b964"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.4.0+0/SPIRV_Tools.v2025.4.0.aarch64-apple-darwin.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
git-tree-sha1 = "8cbe1607d64a560eec13187c7ea2c33643ecc208"
os = "freebsd"

    [[SPIRV_Tools.download]]
    sha256 = "0461714c80cb8dd9c265904c669617da1aa1c0119a61707cc738548db1b541a3"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.4.0+0/SPIRV_Tools.v2025.4.0.x86_64-unknown-freebsd.tar.gz"
[[SPIRV_Tools]]
arch = "aarch64"
git-tree-sha1 = "4010c21242431a051107c7f67ea1caec496816e7"
os = "freebsd"

    [[SPIRV_Tools.download]]
    sha256 = "2035e6e60e4e44387af5bc59caf49bd6a061892131b24622e45c664440ae8edb"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.4.0+0/SPIRV_Tools.v2025.4.0.aarch64-unknown-freebsd.tar.gz"
[[SPIRV_Tools]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c803d0265315981797bc638396e7ec13d33de781"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "6c89c41b881bde8f554b92be1692d0956284cfffd879606b000d36e48994c0c7"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.4.0+0/SPIRV_Tools.v2025.4.0.i686-w64-mingw32-cxx11.tar.gz"
[[SPIRV_Tools]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57d0adb7eb3949f293df5b55c8f2784818bab8b4"
os = "windows"

    [[SPIRV_Tools.download]]
    sha256 = "0f01d30f03654f16c6a5498a457c71f00b358740d2394d2aadfd0b409f051d44"
    url = "https://github.com/JuliaBinaryWrappers/SPIRV_Tools_jll.jl/releases/download/SPIRV_Tools-v2025.4.0+0/SPIRV_Tools.v2025.4.0.x86_64-w64-mingw32-cxx11.tar.gz"
