# Autogenerated wrapper script for SPIRV_Tools_jll for aarch64-apple-darwin
export libSPIRV_Tools, libSPIRV_Tools_diff, libSPIRV_Tools_link, libSPIRV_Tools_lint, libSPIRV_Tools_opt, spirv_as, spirv_cfg, spirv_dis, spirv_link, spirv_lint, spirv_objdump, spirv_opt, spirv_reduce, spirv_val

JLLWrappers.@generate_wrapper_header("SPIRV_Tools")
JLLWrappers.@declare_library_product(libSPIRV_Tools, "@rpath/libSPIRV-Tools.dylib")
JLLWrappers.@declare_library_product(libSPIRV_Tools_diff, "@rpath/libSPIRV-Tools-diff.dylib")
JLLWrappers.@declare_library_product(libSPIRV_Tools_link, "@rpath/libSPIRV-Tools-link.dylib")
JLLWrappers.@declare_library_product(libSPIRV_Tools_lint, "@rpath/libSPIRV-Tools-lint.dylib")
JLLWrappers.@declare_library_product(libSPIRV_Tools_opt, "@rpath/libSPIRV-Tools-opt.dylib")
JLLWrappers.@declare_executable_product(spirv_as)
JLLWrappers.@declare_executable_product(spirv_cfg)
JLLWrappers.@declare_executable_product(spirv_dis)
JLLWrappers.@declare_executable_product(spirv_link)
JLLWrappers.@declare_executable_product(spirv_lint)
JLLWrappers.@declare_executable_product(spirv_objdump)
JLLWrappers.@declare_executable_product(spirv_opt)
JLLWrappers.@declare_executable_product(spirv_reduce)
JLLWrappers.@declare_executable_product(spirv_val)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libSPIRV_Tools,
        "lib/libSPIRV-Tools.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSPIRV_Tools_diff,
        "lib/libSPIRV-Tools-diff.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSPIRV_Tools_link,
        "lib/libSPIRV-Tools-link.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSPIRV_Tools_lint,
        "lib/libSPIRV-Tools-lint.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSPIRV_Tools_opt,
        "lib/libSPIRV-Tools-opt.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        spirv_as,
        "bin/spirv-as",
    )

    JLLWrappers.@init_executable_product(
        spirv_cfg,
        "bin/spirv-cfg",
    )

    JLLWrappers.@init_executable_product(
        spirv_dis,
        "bin/spirv-dis",
    )

    JLLWrappers.@init_executable_product(
        spirv_link,
        "bin/spirv-link",
    )

    JLLWrappers.@init_executable_product(
        spirv_lint,
        "bin/spirv-lint",
    )

    JLLWrappers.@init_executable_product(
        spirv_objdump,
        "bin/spirv-objdump",
    )

    JLLWrappers.@init_executable_product(
        spirv_opt,
        "bin/spirv-opt",
    )

    JLLWrappers.@init_executable_product(
        spirv_reduce,
        "bin/spirv-reduce",
    )

    JLLWrappers.@init_executable_product(
        spirv_val,
        "bin/spirv-val",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
